### ISSUE TITLE
Hardcoded drive letter (Win32)

### ISSUE THREAD

**Issue by snobu** [engineerd/configurator#1]
https://github.com/engineerd/configurator/blob/master/src/configurator.ts#L87

```typescript
export function binPath(): string {
    let baseLocation: string;
    if (process.platform === 'win32') {
        // On windows use the USERPROFILE env variable
        baseLocation = process.env['USERPROFILE'] || 'C:\\';
```

There's no guarantee there will be such a thing as a `C:` drive on Windows. I'd say play it safe, use `%TEMP%`, `%TMP%` or `%HOMEDRIVE%`, these are usually sane and point to a valid location.

**Comment by radu-matei** [comment]
Both `USERPROFILE` and `C:\\` seem to be present in workers, but that's a good idea.

**Comment by radu-matei** [comment]
Thinking about this some more, it looks like long after the Earth is gone, Windows will still have a `C:/` drive.
Closing for now, but feel free to reopen if this is an issue in the future.
