### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by RichiCoder1** [engineerd/configurator#12]
Was testing out the new GitHub Releases feature (thanks!), and twice do to some still-waking-up issues managed to misspell or malform the `with`. Would be nice to get some basic validation. Like if `fromGithubReleases` is provided, error if either `repo`, `version`, or `urlTemplate` is not present.

**Comment by radu-matei** [comment]
That makes sense, thanks for reporting.
I added some initial validation in #13, let me know if the current checks make sense, and if you can think of others.

Thanks!
