### ISSUE TITLE
Update to Node.js 20

### ISSUE THREAD

**Issue by i2van** [engineerd/configurator#49]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: engineerd/configurator@v0.0.10. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by RohanNagar** [comment]
Is this package still maintained? Any alternatives?

**Comment by i2van** [comment]
@RohanNagar I use this [one](https://github.com/Alex079/setup-custom-tool) ([example](https://github.com/i2van/ArknightsLINQPad/blob/3592dadf184995a97459b952aa21d6f9c3cb1a59/.github/workflows/build.yml#L27)). It extracts the whole archive instead of a single one.
